name: folder_structure
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# =============== packages ===================
dependencies:
  flutter:
    sdk: flutter

  # utility packages
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.3

  # icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # state management
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_storage: ^11.6.0
  flutter_native_splash: ^2.3.9

  # product specific

# =============== packages- END ===================

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

# assets:
#=============== Local Assets ===================
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/


# =============== Local Fonts ===================
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600


